### ISSUE TITLE
any way to specify accepted filetypes ?

### ISSUE THREAD

**Issue by Remi-Tribia** [mishazawa/leva-file-picker#3]
Hi,

Is there any way to specify accepted file types, something like

```js
pluginFile({ onChange, accept: { "text/csv": [".csv"] } })
```

Cheers!

**Comment by mishazawa** [comment]
Hi. It is possible to add this feature. 

I didn't get format which you described. What is the purpose of key/value?

Basically, internal stuff is just to set `accept` attribute to `<input />`. 
Example: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept)
```js
pluginFile({ onChange, accept: ".csv,.json" } })
```

**Comment by Remi-Tribia** [comment]
Hi, well that's the format required by react-dropzone : https://react-dropzone.js.org/#!/Accepting%20specific%20file%20types

I've come up with a quick workaround in File.tsx by adding this on line 27:
```js
  const { getRootProps, getInputProps, isDragAccept } = useDropzone({
    accept: {
      "image/jpeg": [".jpg", ".jpeg"],
      "image/png": [".png"]
    },
    maxFiles: 1,
    onDrop,
    disabled
  });
```

but this is hard coded, being able to add it as you mentioned would be great!

EDIT: damn I see you already pushed a commit, you're fast ^^ Cheers 🍻!

**Comment by mishazawa** [comment]
For me it worked with attribute format. Btw, it can be `accept: string | Record<string, string[]>` format. 
I'll update it as soon as figure out how to build it for npm

**Comment by mishazawa** [comment]
After several approaches to build it, only `dropzone` format survived. Updated docs and npm package.

**Comment by Remi-Tribia** [comment]
Thank you so much for your help!

I noticed that `onChange(_file)` is called at initialization with `_file = { accept: { "image/jpeg": [".jpg", ".jpeg"], "image/png": [".png"] } }` and is displayed as if `value` was defined in `File.tsx`.

It only happens at init, afterwards when selecting an actual file, `_file = File`, and when cliking on the cross to unload, `_file = undefined` as it should be.

EDIT: it seems to work ok with the following modification on line 7 in `file-props.ts` :

```js
export const normalize = (
  input: { onChange: (f: any) => void, accept?: Accept }
) => {
  return {
    value: input.onChange, // instead of just `input`
    settings: { accept: input?.accept }
  };
};
```

**Comment by mishazawa** [comment]
added
